SET SERVEROUTPUT ON
SET LINESIZE 200
SET PAGESIZE 200

DECLARE
    v_sql VARCHAR2(1000);
    v_count NUMBER;
BEGIN
    FOR t IN (SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME) LOOP
	v_sql := 'SELECT COUNT(*) FROM ' ||t.TABLE_NAME;
	EXECUTE IMMEDIATE v_sql INTO v_count;
	DBMS_OUTPUT.PUT_LINE('Table: ' ||t.TABLE_NAME || ' - Rows: ' || v_count);
    END LOOP;
END;
/
