SET LINESIZE 200
SET PAGESIZE 200
COLUMN TABLE_NAME FORMAT A20
COLUMN CONSTRAINT_NAME FORMAT A30
COLUMN CONSTRAINT_TYPE FORMAT A15
COLUMN SEARCH_CONDITION FORMAT A50

SELECT 
    TABLE_NAME, 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE,
    SEARCH_CONDITION
FROM 
    USER_CONSTRAINTS
ORDER BY 
    TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME;