SET LINESIZE 200
SET PAGESIZE 200
COLUMN TRIGGER_NAME FORMAT A30
COLUMN TABLE_NAME FORMAT A20
COLUMN TRIGGERING_EVENT FORMAT A20

SELECT 
    TRIGGER_NAME, 
    TABLE_NAME, 
    TRIGGERING_EVENT
FROM 
    USER_TRIGGERS
ORDER BY 
    TABLE_NAME, TRIGGER_NAME;